version: '3.1'

services:
  run-up-api:
    container_name: run-up-api
    build: .
    command: yarn start
    environment:
      PORT: 7000
      REDIS_URL: redis://run-up-redis:6379
      PROD_REDIS_URL: redis://142.93.33.162:6379
    ports:
      - "7000:7000"
    networks:
      - runupto-redis_cache-network

networks:
  runupto-redis_cache-network:
    external: true
