version: '3.1'

services:
  run-up-api:
    container_name: run-up-api
    build: .
    command: yarn start
    environment:
      PORT: 7000
      REDIS_URL: redis://run-up-cache:6379
    ports:
      - "7000:7000"
    networks:
      - cache_cache-network

networks:
  cache_cache-network:
    external: true
